Add diverse deid
Sage-Bionetworks/nlp-sandbox-schemas pull request #78
Opened 2020-11-18 06:45 UTC by cascadianblue

Allow callers of the de-identifer server to specify arbitrary combinations of annotation types and de-identification strategies.

2020-11-18 19:20 UTC, tschaffter commented on openapi/phi-deidentifier/paths/deidentified-note.yaml
> +      '200':
POST should return the status 201 (already corrected in some of the other API)

2020-11-18 19:30 UTC, tschaffter requested changes

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/responses/DeidentifyResponse.yaml
> +description: response to deidentification request, including annotations with indexes in both the original note and the
- Start `description` with a capital letter
- Try to keep it as concise as possible

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/responses/DeidentifyResponse.yaml
> +    $ref: ../../../commons/components/schemas/Annotation.yaml
It looks like we can't add a description to properties that use `$ref`, see https://github.com/OAI/OpenAPI-Specification/issues/1514

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/schemas/DeidentificationConfig.yaml
> +type: object
- Add object description

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/schemas/DeidentificationConfig.yaml
> +            maxLength: 1
- Add `minLength: 1`

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/schemas/DeidentificationConfig.yaml
> +        - "STREET_ADDRESS"
Use:
- `text_date`
- `text_person_name`
- `text_physical_address`

These names are consistent with the properties of the Annotation.yaml object. We use lower snake case for enum.

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/components/schemas/DeidentifyRequest.yaml
> +  deidentifications:
What about renaming to be more descriptive, e.g. `deidentificationStrategies` or `deidentificationConfigurations`?

The selected property name should be the plural version of the schema name used for the `items`.

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/paths/deidentified-note.yaml
> +post:
Rename file to `deidentifiedNote.yaml`

2020-11-18 19:30 UTC, tschaffter commented on openapi/phi-deidentifier/paths/deidentified-note.yaml
> +  operationId: "deidentified_note.read"
Rename operationId to `deidentifiedNote.read`

2020-11-20 08:51 UTC, cascadianblue commented on openapi/phi-deidentifier/components/responses/DeidentifyResponse.yaml
> +    $ref: ../../../commons/components/schemas/Annotation.yaml
Is there some way I can clarify what these properties represent, other than through their field names?

2020-11-20 08:54 UTC, cascadianblue commented
There was one linter warning I wasn't sure how to get rid of:

```
  Message :   operationIds must follow case convention: lower_camel_case
  Path    :   paths./deidentifiedNote.post.operationId
  Line    :   33
```

Any idea how to deal with that?

2020-11-20 14:37 UTC, merged